"""member_no globally unique

Revision ID: 0dcff764263a
Revises: 29c64ca774bc
Create Date: 2026-09-16 18:54:16.819407

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0dcff764263a'
down_revision: Union[str, Sequence[str], None] = '29c64ca774bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_member_no_division'), 'members', type_='unique')
    op.drop_index(op.f('ix_members_member_no'), table_name='members')
    op.create_index(op.f('ix_members_member_no'), 'members', ['member_no'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_members_member_no'), table_name='members')
    op.create_index(op.f('ix_members_member_no'), 'members', ['member_no'], unique=False)
    op.create_unique_constraint(op.f('uq_member_no_division'), 'members', ['member_no', 'division_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
