"""votes.proxy_name, proxy_member_no

Revision ID: 17206b55c422
Revises: ef26811581b9
Create Date: 2026-09-17 16:18:33.767428

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17206b55c422'
down_revision: Union[str, Sequence[str], None] = 'ef26811581b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # 既有資料列需要 server_default 才能加 NOT NULL，加完再移除 default
    op.add_column('votes', sa.Column('proxy_name', sa.String(length=128), nullable=False, server_default=''))
    op.alter_column('votes', 'proxy_name', server_default=None)
    op.add_column('votes', sa.Column('proxy_member_no', sa.String(length=64), nullable=False, server_default=''))
    op.alter_column('votes', 'proxy_member_no', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('votes', 'proxy_member_no')
    op.drop_column('votes', 'proxy_name')
    # ### end Alembic commands ###
