"""division officers

Revision ID: 4b69eefadf7f
Revises: 1493459ecd41
Create Date: 2026-09-21 16:40:42.045399

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b69eefadf7f'
down_revision: Union[str, Sequence[str], None] = '1493459ecd41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('divisions', sa.Column('chair_candidate_id', sa.Integer(), nullable=True))
    op.add_column('divisions', sa.Column('vice_candidate_id', sa.Integer(), nullable=True))
    op.add_column('divisions', sa.Column('officers_manual', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.alter_column('divisions', 'officers_manual', server_default=None)
    op.create_foreign_key(None, 'divisions', 'candidates', ['vice_candidate_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'divisions', 'candidates', ['chair_candidate_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'divisions', type_='foreignkey')
    op.drop_constraint(None, 'divisions', type_='foreignkey')
    op.drop_column('divisions', 'officers_manual')
    op.drop_column('divisions', 'vice_candidate_id')
    op.drop_column('divisions', 'chair_candidate_id')
    # ### end Alembic commands ###
