"""init schema

Revision ID: c68936b6cd6f
Revises: 
Create Date: 2026-09-06 12:44:05.078552

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c68936b6cd6f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=128), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('must_change_password', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admins_username'), 'admins', ['username'], unique=True)
    op.create_table('divisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('min_votes', sa.Integer(), nullable=False),
    sa.Column('max_votes', sa.Integer(), nullable=False),
    sa.Column('opens_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closes_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('color', sa.String(length=16), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_divisions_code'), 'divisions', ['code'], unique=True)
    op.create_table('appointments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('division_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('term', sa.String(length=64), nullable=False),
    sa.Column('appointed_by', sa.String(length=128), nullable=False),
    sa.Column('is_confirmed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['division_id'], ['divisions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_appointments_division_id'), 'appointments', ['division_id'], unique=False)
    op.create_table('candidates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('division_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('avatar_url', sa.String(length=512), nullable=False),
    sa.Column('slogan', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('term_count', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['division_id'], ['divisions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candidates_division_id'), 'candidates', ['division_id'], unique=False)
    op.create_table('members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('member_no', sa.String(length=64), nullable=False),
    sa.Column('name_trad', sa.String(length=128), nullable=False),
    sa.Column('name_simp', sa.String(length=128), nullable=False),
    sa.Column('division_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['division_id'], ['divisions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('member_no', 'division_id', name='uq_member_no_division')
    )
    op.create_index(op.f('ix_members_division_id'), 'members', ['division_id'], unique=False)
    op.create_index(op.f('ix_members_member_no'), 'members', ['member_no'], unique=False)
    op.create_table('rounds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('round_no', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('min_votes', sa.Integer(), nullable=False),
    sa.Column('max_votes', sa.Integer(), nullable=False),
    sa.Column('anonymous', sa.Boolean(), nullable=False),
    sa.Column('opens_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closes_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('allowed_member_nos', sa.Text(), nullable=True),
    sa.Column('is_runoff', sa.Boolean(), nullable=False),
    sa.Column('parent_round_id', sa.Integer(), nullable=True),
    sa.Column('division_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['division_id'], ['divisions.id'], ),
    sa.ForeignKeyConstraint(['parent_round_id'], ['rounds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rounds_status'), 'rounds', ['status'], unique=False)
    op.create_table('round_candidates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('round_id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('division_id', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
    sa.ForeignKeyConstraint(['division_id'], ['divisions.id'], ),
    sa.ForeignKeyConstraint(['round_id'], ['rounds.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('round_id', 'candidate_id', name='uq_round_candidate')
    )
    op.create_index(op.f('ix_round_candidates_candidate_id'), 'round_candidates', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_round_candidates_division_id'), 'round_candidates', ['division_id'], unique=False)
    op.create_index(op.f('ix_round_candidates_round_id'), 'round_candidates', ['round_id'], unique=False)
    op.create_table('votes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('round_id', sa.Integer(), nullable=False),
    sa.Column('member_no', sa.String(length=64), nullable=False),
    sa.Column('member_name', sa.String(length=128), nullable=False),
    sa.Column('division_id', sa.Integer(), nullable=False),
    sa.Column('is_proxy', sa.Boolean(), nullable=False),
    sa.Column('proxy_note', sa.String(length=255), nullable=False),
    sa.Column('min_votes_at_vote', sa.Integer(), nullable=False),
    sa.Column('max_votes_at_vote', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['division_id'], ['divisions.id'], ),
    sa.ForeignKeyConstraint(['round_id'], ['rounds.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('round_id', 'member_no', name='uq_vote_round_member')
    )
    op.create_index(op.f('ix_votes_division_id'), 'votes', ['division_id'], unique=False)
    op.create_index(op.f('ix_votes_member_no'), 'votes', ['member_no'], unique=False)
    op.create_index(op.f('ix_votes_round_id'), 'votes', ['round_id'], unique=False)
    op.create_table('vote_candidates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vote_id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
    sa.ForeignKeyConstraint(['vote_id'], ['votes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vote_id', 'candidate_id', name='uq_vote_candidate')
    )
    op.create_index(op.f('ix_vote_candidates_candidate_id'), 'vote_candidates', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_vote_candidates_vote_id'), 'vote_candidates', ['vote_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vote_candidates_vote_id'), table_name='vote_candidates')
    op.drop_index(op.f('ix_vote_candidates_candidate_id'), table_name='vote_candidates')
    op.drop_table('vote_candidates')
    op.drop_index(op.f('ix_votes_round_id'), table_name='votes')
    op.drop_index(op.f('ix_votes_member_no'), table_name='votes')
    op.drop_index(op.f('ix_votes_division_id'), table_name='votes')
    op.drop_table('votes')
    op.drop_index(op.f('ix_round_candidates_round_id'), table_name='round_candidates')
    op.drop_index(op.f('ix_round_candidates_division_id'), table_name='round_candidates')
    op.drop_index(op.f('ix_round_candidates_candidate_id'), table_name='round_candidates')
    op.drop_table('round_candidates')
    op.drop_index(op.f('ix_rounds_status'), table_name='rounds')
    op.drop_table('rounds')
    op.drop_index(op.f('ix_members_member_no'), table_name='members')
    op.drop_index(op.f('ix_members_division_id'), table_name='members')
    op.drop_table('members')
    op.drop_index(op.f('ix_candidates_division_id'), table_name='candidates')
    op.drop_table('candidates')
    op.drop_index(op.f('ix_appointments_division_id'), table_name='appointments')
    op.drop_table('appointments')
    op.drop_index(op.f('ix_divisions_code'), table_name='divisions')
    op.drop_table('divisions')
    op.drop_index(op.f('ix_admins_username'), table_name='admins')
    op.drop_table('admins')
    # ### end Alembic commands ###
