"""candidate.name_en

Revision ID: ef26811581b9
Revises: 0dcff764263a
Create Date: 2026-09-17 14:21:21.399103

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef26811581b9'
down_revision: Union[str, Sequence[str], None] = '0dcff764263a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidates', sa.Column('name_en', sa.String(length=128), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidates', 'name_en')
    # ### end Alembic commands ###
